name: CI
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  s390:
    name: test s390x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'eminence/terminal-size'
          ref: 'v0.1.17'
          fetch-depth: '0'
      - run: rustup target add s390x-unknown-linux-gnu
      - run: cargo check --all-targets --target s390x-unknown-linux-gnu

  build:
    if: false
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: [1.48.0, stable, beta, nightly]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: maxim-lobanov/setup-xcode@v1
        if: ${{ matrix.os == 'macos-latest' && matrix.toolchain == '1.48.0' }}
        with:
          xcode-version: 13
      - name: Cargo build
        run: cargo build

  cross:
    if: false
    name: Cross
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [1.48.0, stable, beta, nightly]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install toolchain and targets
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: aarch64-linux-android,i686-unknown-linux-gnu
      - name: Cargo check (aarch64)
        run: cargo check --target aarch64-linux-android
      - name: Cargo check (i686)
        run: cargo check --target i686-unknown-linux-gnu

  test:
    if: false
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install faketty
        run: cargo install faketty
      - name: Cargo test (under faketty)
        run: faketty cargo test -- --nocapture
